### ISSUE TITLE
Dashboard on mobile view buggy

### ISSUE THREAD

**Issue by kkay82** [epratt5/NCR-Sandbox#15]
Widgets don't scale properly.

Banner text is overlapping (see teams photo, sorry!)

**Comment by epratt5** [comment]
I think I need to duplicate the dashboard with mobile view design. There doesn't seem to be an easy way to make the dashboard show a mobile view without designing it that way on purpose.

**Comment by kkay82** [comment]
Found this - https://doc.arcgis.com/en/dashboards/reference/dashboards-on-your-smartphone.htm

If you have to redesign, I guess the thought is field users don't need as much information as policy groups or EOC folks. As long as we can show the map, the capacity widget, and the recently updated widget we should be fine.

**Comment by epratt5** [comment]
@kkay82 I'm almost done with redesigning it. I'll send it over as soon as I can for your feedback.

**Comment by epratt5** [comment]
Mobile View Item Details page: [https://napsg.maps.arcgis.com/home/item.html?id=28185f758c374753a3240ab05084ce85](url)

**Comment by epratt5** [comment]
Let me know if there's too much text still on mobile view. I think it works a lot better already.
