### ISSUE TITLE
Enable zooming on mobile

### ISSUE THREAD

**Issue by kkay82** [epratt5/NCR-Sandbox#16]
Text is pretty small without being able to zoom in on mobile via pinch/zoom.

**Comment by epratt5** [comment]
It seems to be working for me. I'll ask the team to check for it.

**Comment by epratt5** [comment]
I'm really not sure how to address this issue...
I'm researching it without much luck at this point.

**Comment by kkay82** [comment]
Closing for now. Will revisit if people use the sandbox on mobile/in the field for training and have issues with text size.
