### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by epratt5** [epratt5/NCR-Sandbox#5]
Make sure all the metadata is filled out.

**Comment by epratt5** [comment]
@kkay82 Will you please let me know if I'm missing anything for the metadata as you go through my Sandbox items? I added you to this [Sandbox group](https://napsg.maps.arcgis.com/home/group.html?id=67808a039527432197499f016b954e85#overview) where I've placed all the applications for now. Please let me know if you can't access anything or find the item details pages for the feature layers or web maps.

**Comment by kkay82** [comment]
Took a stab at it. Will review again later.
