### ISSUE TITLE
Home Page Features

### ISSUE THREAD

**Issue by epratt5** [epratt5/NCR-Sandbox#6]
Get a QR code.
Get with Kevin to figure out a video.
Figure out contact email.

**Comment by epratt5** [comment]
QR code is done.

**Comment by kkay82** [comment]
Contact email is fine how you have it. Remove telephone number.

I made edits to the Technical User Guide for GIS/IT - I had missed that one before. Let's make sure we verify the GitHub link works after Stephany @ NCR takes ownership. If not, change the link.

For the Training Video Playlist, just add "Coming Soon" and make sure the button doesn't go anywhere. I will work on those videos at some point.

**Comment by kkay82** [comment]
The tech user guide for GIS/IT now shows deprecated - not sure why that shows up.

**Comment by epratt5** [comment]
It's supposed to point to the item that ends with a17f4, instead of 495de. I must have missed that for the desktop view. It looks correct to me from the mobile view. I'll verify on the computer.

**Comment by epratt5** [comment]
Fixed. Just need a video. @kkay82 You can close this if you want before the video is done, because I have the placeholder button set up in EB.

**Comment by kkay82** [comment]
Added video playlist.
