### ISSUE TITLE
Including the USGS National Water Dashboard

### ISSUE THREAD

**Issue by kkay82** [epratt5/NCR-Sandbox#7]
We should include this in our sandbox/applications:

https://dashboard.waterdata.usgs.gov/app/nwd/?region=lower48

Not sure what the best solution is. We may want to move to the experience builder-like delivery method. We can discuss this at our next meeting.

**Comment by epratt5** [comment]
I tried to embed this into the Sandbox EB, but it won't let me. "It may restrict the embedding from other sites."

**Comment by kkay82** [comment]
Remove USGS Water Dashboard. Didn't mean to include it here in this application.
